root:
  services:
    minesweeper:
      board5x5x5:
        factory: "default_MinesweeperService" #si no esta definido usa el principal
        configuration:
          bomblocator: "root.bomblocator.fixed5x5x5"
          gamedal: "root.dals.gamedal.inmemory"
      board5x5x3:
        factory: "default_MinesweeperService" #si no esta definido usa el principal
        configuration:
          bomblocator: "root.bomblocator.fixed5x5x3"
          gamedal: "root.dals.gamedal.inmemory"
  dals:
    gamedal:
      inmemory:
        factory: "inmemory_GameDal"

  bomblocator:
    fixed5x5x5:
      factory: "fixed_BombLocator"
      configuration:
        bombs:
          - "0,0"
          - "0,4"
          - "4,0"
          - "4,4"
          - "2,2"
    fixed5x5x3:
      factory: "fixed_BombLocator"
      configuration:
        bombs:
          - "4,0"
          - "4,4"
          - "2,2"
