root:
  services:
    minesweeper:
      default:
        factory: "default_MinesweeperService" #si no esta definido usa el principal
        configuration:
          mineslocator: "root.mineslocator.random"
          gamedal: "root.dals.gamedal.default"

      local:
        factory: "default_MinesweeperService" #si no esta definido usa el principal
        configuration:
          mineslocator: "root.mineslocator.fixed"
          gamedal: "root.dals.gamedal.inmemory"
  dals:
    gamedal:
      default:
        factory: "db_GameDal"
        configuration:
          connectionstring: "cnn"

      inmemory:
        factory: "inmemory_GameDal"

  mineslocator:
    random:
      factory: "random_MinesLocator"
    fixed:
      factory: "fixed_MinesLocator"
      configuration:
        - "1,1"
        - "1,2"
        - "1,3"










