root:
  startup:
    minesweeper: "root.services.minesweeper.default"

  services:
    minesweeper:
      default:
        factory: "default_MinesweeperService"
        configuration:
          mineslocator: "root.mineslocator.random"
          gamedal: "root.dals.gamedal.inmemory"

      local:
        factory: "default_MinesweeperService"
        configuration:
          mineslocator: "root.mineslocator.fixed2"
          gamedal: "root.dals.gamedal.inmemory"
  dals:
    gamedal:
      default:
        factory: "db_GameDal"
        configuration:
          connectionstring: "cnn"

      inmemory:
        factory: "inmemory_GameDal"

  mineslocator:
    random:
      factory: "random_MinesLocator"
    fixed:
      factory: "fixed_MinesLocator"
      configuration:
        mines:
          - "0,0"
          - "0,4"
          - "4,0"
          - "4,4"
          - "2,2"
    fixed2:
      factory: "fixed_MinesLocator"
      configuration:
        mines:
          - "2,1"
          - "2,2"
          - "2,3"









