root:
  services:
    minesweeper:
      default:
        factory: "default_MinesweeperService" #si no esta definido usa el principal
        configuration:
          bomblocator: "root.bomblocator.random"
          gamedal: "root.dals.gamedal.inmemory"

  dals:
    gamedal:
      db:
        factory: "db_GameDal"
        configuration:
          connectionstring: "cnn"

      inmemory:
        factory: "inmemory_GameDal"

  bomblocator:
    random:
      factory: "random_BombLocator"
