root:
  startup:
    minesweeper: "root.services.minesweeper.default"

  services:
    minesweeper:
      default:
        factory: "default_MinesweeperService"
        configuration:
          mineslocator: "root.mineslocator.random"
          gamedal: "root.dals.gamedal.inmemory"

  dals:
    gamedal:
      inmemory:
        factory: "inmemory_GameDal"

  mineslocator:
    random:
      factory: "random_MinesLocator"










